### ISSUE TITLE
error manage init

### ISSUE THREAD

**Issue by azulandres** [litnimax/astconfman#18]
./manage.py init
/root/astconfman/env/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from app import app, db, migrate, user_datastore
  File "/root/astconfman/astconfman/app.py", line 40, in <module>
    from flask_bootstrap import Bootstrap
ImportError: No module named flask_bootstrap

**Comment by litnimax** [comment]
pip install flask-bootstrap.
Fixed in latest commit.

**Comment by azulandres** [comment]
ok, thanks
