### ISSUE TITLE
./manage.py init

### ISSUE THREAD

**Issue by lex68** [litnimax/astconfman#20]
(env)root@OpenMeetings:/var/www/astconfman/astconfman# ./manage.py init
/var/www/astconfman/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
/var/www/astconfman/env/local/lib/python2.7/site-packages/flask_admin/model/base.py:1139: UserWarning: Fields missing from ruleset: participants,logs
  warnings.warn(text)
/var/www/astconfman/env/local/lib/python2.7/site-packages/flask_admin/model/base.py:1139: UserWarning: Fields missing from ruleset: participants,user,logs
  warnings.warn(text)
/var/www/astconfman/env/local/lib/python2.7/site-packages/flask_admin/model/base.py:1139: UserWarning: Fields missing from ruleset: user
  warnings.warn(text)

**Comment by litnimax** [comment]
And what?
These are warnings. Ignore them for now.
