### ISSUE TITLE
asterisk/confprofile - NOTAUTH

### ISSUE THREAD

**Issue by lex68** [litnimax/astconfman#22]
Hi!
GET http://{AST_IP}:5000/asterisk/confprofile/601 - NOTAUTH

Asterisk server not authorized to call URLs - check config.py

Can be more? There is documentation on setting up?

**Comment by litnimax** [comment]
Please see config.py

```
# ASTERISK_IPADDR - IP Address of Asterisk server. All other requests will be denied.
ASTERISK_IPADDR = '127.0.0.1'
```

**Comment by lex68** [comment]
my config.py (asterisk IP - 127.0.0.1)

# *-* encoding: utf-8 *-*
import os
from flask.ext.babelex import lazy_gettext as _

LANGUAGE = 'ru'


SECRET_KEY = '*supersecretkey*'

BRAND_NAV = u'Asterisk Conference Manager'

BRAND_FOOTER = _(u"""(C) 2015 Asterisk Guru | <a href="http://asteriskguru.ru/">www.asteriskguru.ru</a> | Professional Asterisk support & development service

BRAND_LOGO = 'static/logo.png'

BRAND_LOGO_URL = 'http://www.pbxware.ru/'


ASTERISK_IPADDR = '127.0.0.1'


LISTEN_ADDRESS = '0.0.0.0'


LISTEN_PORT = 5000



DEBUG = False


SQLALCHEMY_ECHO = True


DATABASE_FILE = os.path.join(os.path.dirname(__file__), 'astconfman.db')
SQLALCHEMY_DATABASE_URI = 'sqlite:///' + DATABASE_FILE

WTF_CSRF_ENABLED = False

SECURITY_REGISTERABLE = False
SECURITY_RECOVERABLE = False
SECURITY_SEND_PASSWORD_CHANGE_EMAIL = False
SECURITY_USER_IDENTITY_ATTRIBUTES = 'username'
SECURITY_PASSWORD_HASH = 'sha512_crypt'
SECURITY_PASSWORD_SALT = 'bla-bla-bla'


ASTERISK_SPOOL_DIR = '/var/spool/asterisk/outgoing/'
ASTERISK_MONITOR_DIR = '/var/spool/asterisk/monitor/'
ASTERISK_EXECUTABLE = '/usr/sbin/asterisk'
ASTERISK_SSH_ENABLED = False
ASTERISK_SSH_PORT = '22'
ASTERISK_SSH_HOST = '127.0.0.1'
ASTERISK_SSH_USER = 'ast'
ASTERISK_SSH_KEY = '*supersecretkey*'


DISABLED_TABS = []

CALLOUT_TEMPLATE = """Channel: SIP/%(number)s
Context: confman-bridge
Extension: %(confnum)s
Priority: 1
MaxRetries: 0
RetryTime: 15
WaitTime: 300
Set: participant_name=%(name)s
Set: participant_number=%(number)s
Set: conf_number=%(confnum)s
"""

**Comment by litnimax** [comment]
Ok but what in your extensions.conf?
CONFMAN_HOST=http://localhost:5000 ???
Or your another IP?
If you have here for example CONFMAN_HOST=http://192.168.0.1:5000 this will not come from 127.0.0.1...

**Comment by lex68** [comment]
CONFMAN_HOST=http://172.16.202.232:5000 
if I connect via SSH to a asterisk server (172.16.202.232) and do:
wget http://127.0.0.1:5000/asterisk/confprofile/601 - OK
wget http://172.16.202.232:5000/asterisk/confprofile/601 - NOTAUTH

I understand that due to this static web interface. It does not display the information online (such as video). I have to manually update the page.

**Comment by litnimax** [comment]
Look just use ASTERISK_IPADDR='172.16.what.ip'?

**Comment by lex68** [comment]
1.
ASTERISK_IPADDR = '172.16.202.232'
CONFMAN_HOST=http://172.16.202.232:5000
Web-interfase is static
GET http://172.16.202.232:5000/asterisk/confprofile/601 - NOTAUTH
SSH -> wget http://172.16.202.232:5000/asterisk/confprofile/601 - OK
SSH -> wget http://localhost:5000/asterisk/confprofile/601 - NOTAUTH

2.
ASTERISK_IPADDR = '172.16.202.232'
CONFMAN_HOST=http://127.0.0.1:5000
Web-interfase is static
GET http://172.16.202.232:5000/asterisk/confprofile/601 - NOTAUTH
SSH -> wget http://172.16.202.232:5000/asterisk/confprofile/601 - OK
SSH -> wget http://localhost:5000/asterisk/confprofile/601 - NOTAUTH
3.
ASTERISK_IPADDR = '127.0.0.1'
CONFMAN_HOST=http://127.0.0.1:5000
Web-interfase is static
GET http://172.16.202.232:5000/asterisk/confprofile/601 - NOTAUTH
SSH -> wget http://172.16.202.232:5000/asterisk/confprofile/601 - NOTAUTH
SSH -> wget http://localhost:5000/asterisk/confprofile/601 - OK
4.
ASTERISK_IPADDR = '127.0.0.1'
CONFMAN_HOST=http://172.16.202.232:5000
Web-interfase is static
GET http://172.16.202.232:5000/asterisk/confprofile/601 - NOTAUTH
SSH -> wget http://172.16.202.232:5000/asterisk/confprofile/601 - NOTAUTH
SSH -> wget http://localhost:5000/asterisk/confprofile/601 - OK

**Comment by lex68** [comment]
It is because of this static web interface?
