### ISSUE TITLE
Номера телефонов в конференции

### ISSUE THREAD

**Issue by Dgonny** [litnimax/astconfman#30]
Добрый день! Огромное спасибо за ваш труд. Вопрос: у меня не отображаются номера участвующие в конференции. Отображаются квадратики и можно открыть выпадающий список. Они и не должны отображаться или я что-то не доделал. Спасибо еще раз за ваш продукт.

**Comment by litnimax** [comment]
Сложно так сказать.
Обновитесь, может поможет?

**Comment by Dgonny** [comment]
Обновился...Будем смотреть

**Comment by Dgonny** [comment]
Добрый день!
К сожалению после обновления все осталось по старому.

**Comment by litnimax** [comment]
Жаль, но я не могу сейчас поддерживать этот продукт.

**Comment by litnimax** [comment]
Попробуйте найти на фрилансе любого питониста кто знает Flask  / Flask-Admin и поставьте ему задачу найти проблему.

**Comment by Dgonny** [comment]
Попробую разобраться. Еще раз спасибо за Ваш труд.

**Comment by asteriskauto** [comment]
@Dgonny у меня была чуть другая проблема - кнопки управления номерами вообще дефолтно не отображались, после рефреша страницы - http://joxi.ru/8AnWObyCq8aojr 
пир 10000 вообще непонятно откуда взялся:)

Система тестовая была сильно загажена, поставил новую чистую убунту 16.04х64 - все норм, из коробки, копипастом из мануала

**Comment by Dgonny** [comment]
Поставил новую чистую систему, настроил все, все работает и отображается.
может для кого полезно будет:
Вызов в конференцию локальных и внешних пользователей:
[confman-dialout]
include => localph
include => extph
[localph]
exten => _XXX,1,Dial(SIP/${EXTEN},60)
exten => _ХXX,2,Set(ret=${CURL(${CONFMAN_HOST}/asterisk/dial_status/${conf_number}/${participant_number}/${DIALSTATUS})})
[extph]
exten => _[78]X.,1,Dial(${DIALOUT_TRUNK1}/${EXTEN},60)
exten => _[78]X.,2,Set(ret=${CURL(${CONFMAN_HOST}/asterisk/dial_status/${conf_number}/${participant_number}/${DIALSTATUS})})
