### ISSUE TITLE
Разделение доступа пользователей к элементам списков

### ISSUE THREAD

**Issue by Roustikov** [litnimax/astconfman#31]
Добрый день! Большое спасибо за систему. 
Столкнулся с проблемой: пользователи (Модераторы конференций) не видят конференц-комнаты, созданные другими Модераторами. Есть ли способ настроить логику построения списков так, чтобы конференции и контакты отдавались всем пользователям, без необходимости вручную добавлять к каждому элементу списка пользователей, у которых есть права на просмотр?

**Comment by litnimax** [comment]
Здравствуйте!
Чтобы это стало возможным надо править код.
В настоящее время я не занимаюсь развитием этого продукта, могу посоветовать только найти фрилансера  (Flask, Flask-admin).

**Comment by Roustikov** [comment]
Поисковая выдача организуется на стороне Flask-admin, верно? Есть ли какая-то точка входа, откуда можно начинать копать?

**Comment by litnimax** [comment]
Смотрите views.py, там где is_accessible.. и role. Можете убрать проверку на роль.

**Comment by Roustikov** [comment]
Нашёл решение. 
Во views.py в классе UserModelView нужно удалить переопределение методов get_query() и get_one(), тогда данные не фильтруются и выводятся для всех одинаково.
To allow users to see each other's Contacts and Conferences you must remove the overrides in views.py - UserModelView - remove or edit get_query() and get_one() methods.
