### ISSUE TITLE
./manage.py init

### ISSUE THREAD

**Issue by Oleg501** [litnimax/astconfman#45]
root@astconfman:/etc/astconfman/astconfman# ./manage.py init
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from app import app, db, migrate, user_datastore
  File "/etc/astconfman/astconfman/app.py", line 14, in <module>
    from flask_sqlalchemy import SQLAlchemy, models_committed
  File "/etc/astconfman/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 27, in <module>
    from sqlalchemy.declarative import DeclarativeMeta, declarative_base
ImportError: No module named declarative

 pip2.7 list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package          Version
---------------- -------
alembic          1.0.8
Babel            2.6.0
blinker          1.4
Click            7.0
dominate         2.3.5
Flask            1.0.2
Flask-Admin      1.3.0
Flask-BabelEx    0.9.3
Flask-Bootstrap  3.3.7.1
Flask-Login      0.4.1
Flask-Mail       0.9.1
Flask-Migrate    2.4.0
Flask-Principal  0.4.0
Flask-Script     2.0.6
Flask-Security   3.0.0
Flask-SQLAlchemy 2.3.2
Flask-WTF        0.14.2
gevent           1.4.0
greenlet         0.4.15
itsdangerous     1.1.0
Jinja2           2.10
Mako             1.0.7
MarkupSafe       1.1.1
passlib          1.7.1
pip              19.0.3
pkg-resources    0.0.0
python-crontab   2.3.6
python-dateutil  2.8.0
python-editor    1.0.4
pytz             2018.9
setuptools       40.8.0
six              1.12.0
speaklater       1.3
SQLAlchemy       1.2.0b3
transliterate    1.10.2
uWSGI            2.0.18
visitor          0.1.3
Werkzeug         0.14.1
wheel            0.33.1
WTForms          2.2.1

Не могу понять что не так :(

**Comment by Turbid** [comment]
Try to recreate the venv with last requirements.txt: https://github.com/litnimax/astconfman/commit/0283f7a342280ff1e4f6b7791e4427eec95edd3d

**Comment by Oleg501** [comment]
Made changes:

./manage.py init
/home/oleg_501/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
/home/oleg_501/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from app import app, db, migrate, user_datastore
  File "/etc/astconfman/astconfman/app.py", line 149, in <module>
    from views import asterisk
  File "/etc/astconfman/astconfman/views.py", line 20, in <module>
    from models import Contact, Conference, ConferenceLog, Participant
  File "/etc/astconfman/astconfman/models.py", line 5, in <module>
    from sqlalchemy_hybrid import hybrid_property
ImportError: No module named sqlalchemy_hybrid

 pip2.7 list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package          Version
---------------- -------
alembic          1.0.8
Babel            2.6.0
blinker          1.4
Click            7.0
dominate         2.3.5
Flask            0.12.4
Flask-Admin      1.3.0
Flask-BabelEx    0.9.3
Flask-Bootstrap  3.3.7.1
Flask-Login      0.4.1
Flask-Mail       0.9.1
Flask-Migrate    2.4.0
Flask-Principal  0.4.0
Flask-Script     2.0.6
Flask-Security   3.0.0
Flask-SQLAlchemy 2.3.2
Flask-WTF        0.14.2
gevent           1.2.2
greenlet         0.4.15
itsdangerous     1.1.0
Jinja2           2.10
Mako             1.0.7
MarkupSafe       1.1.1
passlib          1.7.1
pip              19.0.3
pkg-resources    0.0.0
python-crontab   2.3.6
python-dateutil  2.8.0
python-editor    1.0.4
pytz             2018.9
setuptools       40.8.0
six              1.12.0
speaklater       1.3
SQLAlchemy       1.2.0b3
transliterate    1.10.2
visitor          0.1.3
Werkzeug         0.14.1
wheel            0.33.1
WTForms          2.2.1

**Comment by Turbid** [comment]
Check models.py:
`from sqlalchemy.ext.hybrid import hybrid_property`

**Comment by Oleg501** [comment]
./manage.py init
/home/oleg_501/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
/home/oleg_501/env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from app import app, db, migrate, user_datastore
  File "/etc/astconfman/astconfman/app.py", line 149, in <module>
    from views import asterisk
  File "/etc/astconfman/astconfman/views.py", line 696, in <module>
    name=app.config['BRAND_NAV'],
KeyError: 'BRAND_NAV'

**Comment by Turbid** [comment]
Show `grep BRAND_NAV config.py`

**Comment by Oleg501** [comment]
Удалил все.
Поставил чистый Centos 7.
И все заработало.
Спасибо за помощь!
