### ISSUE TITLE
Проблема с установкой на FreePBX Centos 7

### ISSUE THREAD

**Issue by IYS-SK** [litnimax/astconfman#56]
Здравствуйте. Возникла проблема с установкой на FreePBX. Подскажите что не так? Может есть пример для Free
PBX? 
PBX Version:15.0.17.34
PBX Distro:12.7.8-2011-5.sng7
Asterisk Version:17.7.0
![Screenshot 2021-05-27 135423](https://user-images.githubusercontent.com/84908407/119814772-738ec980-bef3-11eb-92b5-5570823856f4.png)
![Screenshot 2021-05-27 135925](https://user-images.githubusercontent.com/84908407/119815123-e4ce7c80-bef3-11eb-9b0c-43d24400ff32.png)

**Comment by niaproxy** [comment]
Для этого приложения нужен Flask версии 0.12.4. На твоих скринах 1.1.4 создай новую папку env и переставь зависимости:
`` 
pip install -r requirements.txt

**Comment by niaproxy** [comment]
Привет
Если проблема еще актуальна - используй решения из тикета #65
[https://github.com/litnimax/astconfman/issues/65](url)
Похоже на аналогичную проблему с зависимостями.
