### ISSUE TITLE
Problem with installing on CentOS 7 

### ISSUE THREAD

**Issue by VAlyutin** [litnimax/astconfman#65]
Hello.
Having problem with installing astconfman on CentOS 7.
Error during ./manage init.

(env) [root@s-spb-ast astconfman]# ./manage.py init
Traceback (most recent call last):
  File "./manage.py", line 5, in <module>
    from flask_migrate import MigrateCommand
  File "/usr/lib/python2.7/site-packages/flask_migrate/__init__.py", line 7, in <module>
    from alembic import __version__ as __alembic_version__
  File "/usr/lib/python2.7/site-packages/alembic/__init__.py", line 3, in <module>
    from . import context  # noqa
  File "/usr/lib/python2.7/site-packages/alembic/context.py", line 1, in <module>
    from .runtime.environment import EnvironmentContext
  File "/usr/lib/python2.7/site-packages/alembic/runtime/environment.py", line 1, in <module>
    from .migration import MigrationContext
  File "/usr/lib/python2.7/site-packages/alembic/runtime/migration.py", line 5, in <module>
    from sqlalchemy import Column
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/__init__.py", line 8, in <module>
    from . import util as _util
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/_collections.py", line 16, in <module>
    from .compat import binary_types
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 115, in <module>
    import importlib_metadata  # noqa
  File "/usr/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 7, in <module>
    import zipp
  File "/usr/lib/python2.7/site-packages/zipp.py", line 16, in <module>
    from contextlib2 import suppress
  File "/usr/lib/python2.7/site-packages/contextlib2/__init__.py", line 56
    async def __aenter__(self):
            ^
SyntaxError: invalid syntax

(env) [root@s-spb-ast astconfman]# pip freeze
alembic==1.6.5
Babel==2.9.1
backports.ssl-match-hostname==3.5.0.1
blivet==0.61.15.76
cffi==1.6.0
chardet==2.2.1
click==7.1.2
configobj==4.7.2
contextlib2==21.6.0
cryptography==1.7.2
decorator==3.4.0
dnspython==1.12.0
enum34==1.0.4
Flask==0.12.4
Flask-Babel==0.11.2
Flask-BabelEx==0.9.3
Flask-Migrate==3.0.1
Flask-SQLAlchemy==2.5.1
futures==3.1.1
gssapi==1.2.0
idna==2.4
importlib-metadata==3.1.0
iniparse==0.4
ipaclient==4.6.8
ipaddress==1.0.16
ipalib==4.6.8
ipaplatform==4.6.8
ipapython==4.6.8
itsdangerous==1.1.0
Jinja2==2.5
jwcrypto==0.4.2
kitchen==1.1.1
langtable==0.0.31
M2Crypto==0.21.1
Mako==1.1.4
MarkupSafe==1.1.1
netaddr==0.7.5
netifaces==0.10.4
openlmi==0.5.0
openlmi-software==0.5.0
openlmi-storage==0.8.0
perf==0.1
ply==3.4
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pykickstart==1.99.66.22
pyliblzma==0.5.3
pyparsing==1.5.6
pyparted==3.9
python-augeas==0.5.0
python-dateutil==1.5
python-editor==1.0.4
python-ldap==2.4.15
python-linux-procfs==0.4.9
python-nss==0.16.0
python-yubico==1.2.3
pytz==2021.1
pyudev==0.15
pyusb==1.0.0b1
pywbem==0.7.0
pyxattr==0.5.1
PyYAML==3.10
qrcode==5.0.1
requests==2.6.0
schedutils==0.4
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
speaklater==1.3
SQLAlchemy==1.4.21
SSSDConfig==1.16.5
UNKNOWN==0.0.0
urlgrabber==3.10
urllib3==1.10.2
virtualenv==15.1.0
Werkzeug==0.11.10
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4
zipp==1.2.0

Please help

**Comment by niaproxy** [comment]
Hi

> alembic==1.6.5

Check your env again. Last known supported version for alembic is 0.8.6
It probably be best to create new virtualenv:
`virtualenv env2`
and install all requirements again:
`pip install -r requirements.txt`

**Comment by VAlyutin** [comment]
(env) [root@localhost astconfman]# pip freeze
alembic==0.8.6
asterisk-ami==0.1.5
Babel==2.9.1
blinker==1.4
click==7.1.2
dnspython==1.15.0
dominate==2.6.0
email-validator==1.1.3
Flask==0.12.4
Flask-Admin==1.3.0
Flask-BabelEx==0.9.3
Flask-Bootstrap==3.3.7.1
Flask-Login==0.5.0
Flask-Mail==0.9.1
Flask-Migrate==3.0.1
Flask-Principal==0.4.0
Flask-Script==2.0.6
Flask-Security==3.0.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.15.0
gevent==1.2.2
greenlet==1.1.0
idna==2.10
itsdangerous==1.1.0
Jinja2==2.5
Mako==1.1.4
MarkupSafe==1.1.1
passlib==1.7.4
python-crontab==2.5.1
python-dateutil==2.8.2
python-editor==1.0.4
pytz==2021.1
six==1.16.0
speaklater==1.3
SQLAlchemy==1.2.0b3
transliterate==1.10.2
visitor==0.1.3
Werkzeug==0.11.10
WTForms==2.3.3

(env) [root@localhost astconfman]# ./manage.py init
Traceback (most recent call last):
  File "./manage.py", line 5, in <module>
    from flask_migrate import MigrateCommand
ImportError: cannot import name MigrateCommand

**Comment by niaproxy** [comment]
Hi
It appears what upstream version of Flask-Migrate has broken backwards compatibility for this one.
Install previous stable version:
`pip install Flask-Migrate==2.7.0`
Thanks for pointing it out - will make push request with updated requirements.

**Comment by VAlyutin** [comment]
(env) [root@localhost astconfman]# ./manage.py init
Traceback (most recent call last):
  File "./manage.py", line 6, in <module>
    from flask_security import utils
  File "/root/astconfman/env/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/root/astconfman/env/lib/python2.7/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/root/astconfman/env/lib/python2.7/site-packages/flask_security/forms.py", line 17, in <module>
    from flask_wtf import FlaskForm as BaseForm
  File "/root/astconfman/env/lib/python2.7/site-packages/flask_wtf/__init__.py", line 1, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "/root/astconfman/env/lib/python2.7/site-packages/flask_wtf/csrf.py", line 220
    dest = f'{view.__module__}.{view.__name__}'
                                              ^
SyntaxError: invalid syntax

(env) [root@localhost astconfman]# pip freeze
alembic==0.8.6
asterisk-ami==0.1.5
Babel==2.9.1
blinker==1.4
click==7.1.2
dnspython==1.16.0
dominate==2.6.0
email-validator==1.1.3
Flask==0.12.4
Flask-Admin==1.3.0
Flask-BabelEx==0.9.4
Flask-Bootstrap==3.3.7.1
Flask-Login==0.5.0
Flask-Mail==0.9.1
Flask-Migrate==2.7.0
Flask-Principal==0.4.0
Flask-Script==2.0.6
Flask-Security==3.0.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.15.0
gevent==1.2.2
greenlet==1.1.0
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.3
Mako==1.1.4
MarkupSafe==1.1.1
passlib==1.7.4
python-crontab==2.5.1
python-dateutil==2.8.2
python-editor==1.0.4
pytz==2021.1
six==1.16.0
speaklater==1.3
SQLAlchemy==1.2.0b3
transliterate==1.10.2
visitor==0.1.3
Werkzeug==0.11.10
WTForms==2.3.3

**Comment by niaproxy** [comment]
Hi
Try this another one:
Flask-WTF==0.14.3

**Comment by VAlyutin** [comment]
Hi!
So its eventually started!
Working config on CentOS7 for me is:

alembic==0.8.6
asterisk-ami==0.1.5
Babel==2.9.1
blinker==1.4
click==7.1.2
dnspython==1.16.0
dominate==2.6.0
email-validator==1.1.3
Flask==0.12.4
Flask-Admin==1.3.0
Flask-BabelEx==0.9.4
Flask-Bootstrap==3.3.7.1
Flask-Login==0.5.0
Flask-Mail==0.9.1
Flask-Migrate==2.7.0
Flask-Principal==0.4.0
Flask-Script==2.0.6
Flask-Security==3.0.0
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.14.3
gevent==1.2.2
greenlet==1.1.0
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.3
Mako==1.1.4
MarkupSafe==1.1.1
passlib==1.7.4
python-crontab==2.5.1
python-dateutil==2.8.2
python-editor==1.0.4
pytz==2021.1
six==1.16.0
speaklater==1.3
SQLAlchemy==1.2.0b3
transliterate==1.10.2
visitor==0.1.3
Werkzeug==0.11.10
WTForms==2.3.3


Thanks a lot!

**Comment by niaproxy** [comment]
That's good ☺
Btw which version of asterisk you running? I'm interested to now if talker detection in conf room works on later versions e.g. 13+

**Comment by VAlyutin** [comment]
:-))

Запущено на Asterisk 16.17.0 с FreePBX.
Полный функционал пока не проверен, не хватает опыта с этим. Но статус по конференциям отображается и можно управлять участниками (кикать например...)
