### ISSUE TITLE
Нет управления участниками конференции

### ISSUE THREAD

**Issue by VAlyutin** [litnimax/astconfman#68]

**Comment by VAlyutin** [comment]
Добрый день. В конференции нет возможности управлять участниками, в частности включать\отключать микрофон, приглашать в конференцию...
Работает только удаление из конференции.
Помогите пожалуйста, разобраться.

**Comment by niaproxy** [comment]
Привет.
В каталоге asterisk_etc есть пример диал-плана для астериска, в нем описаны все необходимые для работы функции.
Добавь его в свой конфиг по примеру из README:
`#include /path/to/astconfman/asterisk_etc/extensions.conf`
И не забудь указать свой транк в начале:
`DIALOUT_TRUNK1=SIP/trunk`

**Comment by niaproxy** [comment]
И еще проверь что астериск и веб-приложение запущены от одного пользователя.

**Comment by VAlyutin** [comment]
(env) [root@Asterisk astconfman]# ps auxwwww|grep asterisk
root      3098  0.0  0.0 115404   800 ?        S    Aug09   0:00 /bin/sh /usr/sbin/safe_asterisk -U asterisk -G asterisk
asterisk  3100  0.8  4.0 3226364 155716 ?      Sl   Aug09 420:30 /usr/sbin/asterisk -f -U asterisk -G asterisk -vvvg -c
asterisk  3392  0.1  1.5 1208472 58416 ?       Ssl  Aug09  54:01 PM2 v4.5.0: God Daemon (/home/asterisk/.pm2)
asterisk  3442  0.3  0.9 989836 38152 ?        Ssl  Aug09 177:58 node /var/www/html/admin/modules/core/node/fastagi-server.js
asterisk  3822  0.3  3.1 1211072 123404 ?      Ssl  Aug09 189:58 letschat
asterisk  7393  0.3  1.6 1084764 62500 ?       Ssl  09:01   1:05 node /var/www/html/admin/modules/ucp/node/index.js
asterisk  7498  0.0  1.5 746008 58600 ?        S    Sep13   0:10 /usr/sbin/httpd -DFOREGROUND
asterisk  7873  0.0  1.6 745072 62124 ?        S    Sep13   0:13 /usr/sbin/httpd -DFOREGROUND
asterisk 10065  0.0  1.5 747980 59792 ?        S    Sep13   0:12 /usr/sbin/httpd -DFOREGROUND
asterisk 12676  0.0  0.2 198096  8592 ?        Ss   Sep13   0:00 /usr/bin/python /usr/local/bin/pnp_server
asterisk 13310  0.0  1.3 745280 53428 ?        S    10:05   0:03 /usr/sbin/httpd -DFOREGROUND
asterisk 14560  0.0  1.5 748624 59760 ?        S    Sep13   0:10 /usr/sbin/httpd -DFOREGROUND
asterisk 16699  0.0  1.7 752068 67296 ?        S    10:45   0:03 /usr/sbin/httpd -DFOREGROUND
asterisk 16753  0.0  0.6 733224 25624 ?        S    10:45   0:01 /usr/sbin/httpd -DFOREGROUND
asterisk 19761  0.0  1.1 499700 43360 ?        Ss   11:23   0:00 php /var/www/html/admin/modules/restapps/restapps.php
asterisk 21911  0.0  1.2 745312 49316 ?        S    11:50   0:01 /usr/sbin/httpd -DFOREGROUND
asterisk 22023  0.0  0.6 732148 24940 ?        S    11:50   0:00 /usr/sbin/httpd -DFOREGROUND
asterisk 22409  0.0  0.6 732148 24916 ?        S    11:54   0:00 /usr/sbin/httpd -DFOREGROUND
root     25949  0.0  0.0 191880  2368 pts/0    S    12:42   0:00 su - asterisk
asterisk 25950  0.0  0.0 115544  2088 pts/0    S    12:42   0:00 -bash
root     26673  0.0  0.0 191880  2368 pts/0    S    12:50   0:00 su - asterisk
asterisk 26674  0.0  0.0 115544  2128 pts/0    S    12:50   0:00 -bash
root     27184  0.0  0.0 191880  2368 pts/0    S    12:56   0:00 su - asterisk
asterisk 27185  0.0  0.0 115544  2124 pts/0    S    12:56   0:00 -bash
root     28132  0.0  0.0 191880  2368 pts/0    S    13:06   0:00 su - asterisk
asterisk 28133  0.0  0.0 115544  2164 pts/0    S    13:06   0:00 -bash
root     30504  0.0  0.0 191880  2368 pts/0    S    13:39   0:00 su - asterisk
asterisk 30505  0.0  0.0 115544  2120 pts/0    S    13:39   0:00 -bash
asterisk 32389  1.9  1.4 464820 55808 ?        Sl   14:03   0:02 python ./run.py

строку #include /path/to/astconfman/asterisk_etc/extensions.conf добавил в extensions_custom.conf
транк DIALOUT_TRUNK1 прописал

**Comment by niaproxy** [comment]
Запусти "python ./run.py" в терминале и покажи вывод при попытке вызова абонента и мьюте.
Отдельно попробуй управлять конференцией через CLI астериска:
`confbridge mute номер_конференции id_канала`

> /home/asterisk/.pm2
>  node /var/www/html/admin/modules/core/node/fastagi-server.js

Я правильно понимаю что на сервере FreePBX?

**Comment by VAlyutin** [comment]
Да, АТС FreePBX 15.

(env) [root@Asterisk astconfman]# 10.9.13.16 - - [2021-09-14 16:30:49] "GET /user/ HTTP/1.1" 200 13645 0.425065
10.9.13.16 - - [2021-09-14 16:30:49] "GET /favicon.ico HTTP/1.1" 200 1430 0.006189
10.9.13.16 - - [2021-09-14 16:30:52] "GET /admin/conference/ HTTP/1.1" 200 16225 0.135172
10.9.13.16 - - [2021-09-14 16:30:55] "GET /admin/conference/details/?url=%2Fadmin%2Fconference%2F&id=2 HTTP/1.1" 200 19221 0.219409
10.9.13.16 - - [2021-09-14 16:30:55] "GET /asterisk/online_participants.json/199?_=1631625502680 HTTP/1.1" 200 109 0.040273
10.9.13.16 - - [2021-09-14 16:31:12] "GET /admin/conference/2/invite_guest?phone=101 HTTP/1.1" 302 937 1.056964
10.9.13.16 - - [2021-09-14 16:31:12] "GET /admin/conference/details/?id=2 HTTP/1.1" 200 19902 0.067049
10.9.13.16 - - [2021-09-14 16:31:12] "GET /asterisk/online_participants.json/199?_=1631625519604 HTTP/1.1" 200 109 0.022595
10.9.13.16 - - [2021-09-14 16:31:35] "GET /admin/conference/details/?id=2 HTTP/1.1" 200 19221 0.102798
10.9.13.16 - - [2021-09-14 16:31:35] "GET /asterisk/online_participants.json/199?_=1631625542214 HTTP/1.1" 200 275 0.045608
10.9.13.16 - - [2021-09-14 16:31:35] "GET /favicon.ico HTTP/1.1" 200 1430 0.009612
10.9.13.16 - - [2021-09-14 16:31:38] "GET /admin/conference/mute/2/channel/PJSIP/101-000000a6 HTTP/1.1" 302 941 1.152728
10.9.13.16 - - [2021-09-14 16:31:38] "GET /admin/conference/details/?id=2 HTTP/1.1" 200 20084 0.104139
10.9.13.16 - - [2021-09-14 16:31:38] "GET /asterisk/online_participants.json/199?_=1631625545408 HTTP/1.1" 200 276 0.042531

IP странный отображается... АТС на другом...

Через CLI тоже только kick работает...

Asterisk*CLI> confbridge mute 199 all
Muting all from confbridge 199
результата не дает

**Comment by niaproxy** [comment]
> 10.9.13.16 - - [2021-09-14 16:30:49] "GET /user/ HTTP/1.1"
IP адреса  задаются в файле config.py в строках ASTERISK_IPADDR для астериска и LISTEN_ADDRESS для веб-приложения и по умолчанию 127.0.0.1 т.к. предполагается запуск на одном локальном сервере, проверь свой файл.

> Да, АТС FreePBX 15.
> GET /asterisk/online_participants.json/199
Конференция 199 создана через интерфейс веб-приложения или через FreePBX?

> Muting all from confbridge 199
> результата не дает

Вот это уже странно, попробуй прислать вывод `asterisk -rvvv` когда мьютишь абонента. И еще `asterisk -rx 'dialplan show' | grep ConfBridge` на всякий случай.
