### ISSUE TITLE
python-pip python-virtualenv  не найдено кандидатов для установки

### ISSUE THREAD

**Issue by PrimerMMM** [litnimax/astconfman#69]
#apt-get install python-pip python-virtualenv
E: Для архива 'python-pip' не найдено кандидатов для установки
E: Для архива 'python-virtualenv' не найдено кандидатов для установки

Debian 11 все обновлено вот sources.list
deb http://ftp.debian.org/debian bullseye main contrib non-free
deb-src http://ftp.debian.org/debian bullseye main contrib non-free

deb http://ftp.debian.org/debian bullseye-updates main contrib non-free
deb-src http://ftp.debian.org/debian bullseye-updates main contrib non-free

deb http://security.debian.org/debian-security bullseye-security main contrib non-free
deb http://ftp.debian.org/debian bullseye-backports main contrib non-free
deb http://ftp.us.debian.org/debian bullseye-proposed-updates main contrib non-free

Может не там копаю?

**Comment by niaproxy** [comment]
Привет.
В 11 дебиане удалили эти пакеты. Можно поставить pip для python2 вручную:

curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
sudo python2 get-pip.py
sudo pip2 install virtualenv

Дальше все по инструкции.


На Sun, 12 Dec 2021 08:56:29 -0800, PrimerMMM писал:
> #apt-get install python-pip python-virtualenv
> E: Для архива 'python-pip' не найдено кандидатов для установки
> E: Для архива 'python-virtualenv' не найдено кандидатов для установки
>
> Debian 11 все обновлено вот sources.list
> deb http://ftp.debian.org/debian bullseye main contrib non-free
> deb-src http://ftp.debian.org/debian bullseye main contrib non-free
>
> deb http://ftp.debian.org/debian bullseye-updates main contrib non-free
> deb-src http://ftp.debian.org/debian bullseye-updates main contrib non-free
>
> deb http://security.debian.org/debian-security 
> bullseye-security main contrib non-free
> deb http://ftp.debian.org/debian bullseye-backports main contrib non-free
> deb http://ftp.us.debian.org/debian bullseye-proposed-updates 
> main contrib non-free
>
> Может не там копаю?
>
>

 




--

**Comment by PrimerMMM** [comment]
Спасибі тебе, добрый человек!

нд, 12 груд. 2021, 20:26 користувач Ivan Samokhin ***@***.***>
пише:
